### PR TITLE
m_id transceiver member variable

### LINKED ISSUE #3: Change name of buffer to mpi_msg in mpi_listener
Currently the word buffer is used way too much and it is confusing. I would like the word buffer to reflect data that is buffered on the transceiver waiting to be flushed out by receive operations:

https://github.com/gregjhansell97/mpi-radio-transceiver/blob/99721c5eed8ab162d5cc9706fdd4294c4ae05fc9/mpi_radio_transceiver.cpp#L185-L207

The word buffer is also being used in the MPI calls to receive an mpi message. It would be a lot cleaner to call these "mpi_msg"

https://github.com/gregjhansell97/mpi-radio-transceiver/blob/99721c5eed8ab162d5cc9706fdd4294c4ae05fc9/mpi_radio_transceiver.cpp#L57-L81

### LINKED ISSUE #7: Give Transceiver instance a unique id that can be privately accessible: m_id
The transceivers cannot be differentiated. It would be beneficial to uniquely identify transceivers so they do not receive their own messages. The m_id would be assigned in the for loop.

https://github.com/gregjhansell97/mpi-radio-transceiver/blob/99721c5eed8ab162d5cc9706fdd4294c4ae05fc9/mpi_radio_transceiver.h#L35-L58

### PR DESCRIPTION
**Pull request by chrisatang**

### CODE REVIEW

**Review by gregjhansell97 — CHANGES_REQUESTED** [review]
Good job up until handling the received mpi message in mpi_radio_transceiver. The term msg_size is used for the thread loop and receiving messages from MPI, but the buffer of the transceiver remains being called the buffer: because it will store the buffered messages. For example, line 105, t.m_buffer is valid because it is not going to be storing the mpi msg but rather the buffered data.

**Review by gregjhansell97 — COMMENTED** [review]
Sorry I didn't realize this message came through, (my wifi cut out); it was pretty much the samething as commented below in the next review

**Review by gregjhansell97 — COMMENTED** [review]
Perhaps we should make the m_id of type size_t and modify the for-loop variable i too, especially since we may be dealing with a large number of transceivers.

**Comment by chrisatang** [comment]
Check changes.

**Pull request merged**
